; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "BIOS Viewer"
#define MyAppVersion "1.16"
#define MyAppExeName "BiosViewer.exe"
#define MyAppAssocName "Binary File"
#define MyAppAssocExt ".rom"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define PackagePath "C:\Mac\Home\Desktop\BiosViewer"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CBB47880-0760-4161-B423-CCC22CF0D07C}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\BiosViewer
DisableDirPage=yes
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir={#PackagePath}\..\BiosViewerSetup
OutputBaseFilename=BIOS Viewer Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PackagePath}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#PackagePath}\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#PackagePath}\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PackagePath}\Qt6Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PackagePath}\Qt6Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PackagePath}\Qt6Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PackagePath}\Qt6Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PackagePath}\Qt6Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PackagePath}\libcrypto-3-arm64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PackagePath}\generic\*"; DestDir: "{app}\generic"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackagePath}\iconengines\*"; DestDir: "{app}\iconengines"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackagePath}\imageformats\*"; DestDir: "{app}\imageformats"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackagePath}\networkinformation\*"; DestDir: "{app}\networkinformation"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackagePath}\platforms\*"; DestDir: "{app}\platforms"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackagePath}\styles\*"; DestDir: "{app}\styles"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackagePath}\tls\*"; DestDir: "{app}\tls"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackagePath}\tool\*"; DestDir: "{app}\tool"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKCR; Subkey: "*\shell\{#MyAppName}"; ValueType: string; ValueData: "Open With {#MyAppName}"; Flags: uninsdeletekey
Root: HKCR; Subkey: "*\shell\{#MyAppName}"; ValueType: string; ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey
Root: HKCR; Subkey: "*\shell\{#MyAppName}\command"; ValueType: string; ValueData: "{app}\{#MyAppExeName} ""%1"""; Flags: uninsdeletekey

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

